version: "3.9"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.319.3-jdk11
    privileged: true
    user: root
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    volumes:
      - ./jenkins-docker-certs/:/certs/client
      - ./jenkins-data/:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
    restart: always