version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:13.3
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - /var/dockerPostgres/:/docker-entrypoint-initdb.d
      - /var/dockerPostgres/:/var/lib/postgresql/data
      
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@ya.ru"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_LISTEN_ADDRESS: "0.0.0.0"
      PGADMIN_LISTEN_PORT: "80"
    volumes:
      - /var/dockerPostgres/pgadmin/:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: always
networks:
  postgres:
    driver: bridge